### ISSUE TITLE
What is this for?

### ISSUE THREAD

**Issue by rvosa** [naturalis/treebase-artifact#1]
It would be great if the README could explain the purpose of this repository. My impression is that this is intended for pre-compiled binaries that TreeBASE depends on. If that is the case than I can imagine that we are going to store things such as headless Mesquite, and PhyloWidget, here. But then, if we do that we're going to want to have this repo function as a Maven repository, i.e. with the right directory structure under the gh-pages branch.

**Comment by fpieters** [comment]
Indeed this repo will be used for the pre-compiled binaries. My initial idea was to not use this repo function as a Maven repository, since the api's are not supported anymore in the central Maven repository. As far as I know there is no possibility to make a build from source.
